name: clang-format Check
on: [push, pull_request]
jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run clang-format style check for C programs.
      uses: DoozyX/clang-format-lint-action@v0.8
      with:
        source: '.'
        extensions: 'c,h,cpp'
        clangFormatVersion: 10
        style: file
        exclude: './config ./hl/src/H5LTanalyze.c'
